name: grow_forest_using_fitness
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  pedometer: ^4.0.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JetBrains
      fonts:
        - asset: fonts/JetBrainsMono-Bold.ttf
  assets:
    - assets/
